### PR TITLE
Visualise a reference energy system from a Tabular Data Package

### PR DESCRIPTION
**Pull request by willu47**
- Visualises a reference energy system using networkx, graphviz and dot.
- Very useful for debugging purposes e.g. note that the simplicity model shown below has no CO2 emission for Diesel imports, and several orphaned fuels, emissions and technologies.

image

To do:

- [ ] Add to the command-line-interface
- [ ] Add requirements to the package install script
- [ ] Write some tests

### CODE REVIEW

**Comment by tniet** [comment]
Hi Will,

Abhi and I have also done some work on pulling a RES or RRSS together with GraphViz based on a data file...  Abhi has done more work than I have, but I figured out a couple of things that make the RES cleaner and nicer:
     rankdir="LR";  # Makes things horizontal instead of vertical - easier to read.

    # For each fuel, create an invisible box rather than a labelled one.
     Fuel1 [style=invis, height=0, width=0, label=""] # Create an invisible box for each fuel
    
   # And then connect the different technologies to the fuels, with a label on the output.
    PWRWND001 -> Fuel1[dir=none] # The dir=none statement removes the arrow
    Fuel1 -> PWRTRN001[label="Fuel1"];  # And then the fuel lines have a label
This makes the diagram much cleaner and reduces the clutter.

Here's an example that has these features.
RESTest

I can't do it this weekend, but if you can't incorporate these items into your code in the next week I'll try to do that.  It's really nice to be able to create a RES from a data file...

Cheers,
Taco..

**Comment by willu47** [comment]
Ooh, that's very nice. I'll add those changes to the code and update the pull request.

**Comment by willu47** [comment]
Using `rankdir='LR'` cleans up the plot nicely. One issue is that without the labels on fuel 'nodes' it is less useful for debugging, as you cannot identify orphaned nodes.

res

**Comment by willu47** [comment]
@tniet @abhishek0208 - could we come up with a shared implementation of the RES diagram drawing? As you're drawing the RES diagram directly from the MathProg datafile, you must be parsing the AMPL-syntax somehow?  This could be handy for issue #5.

**Comment by tniet** [comment]
Hi @willu47,

I think that having orphaned fuels isn't a big issue.  This only becomes an issue if you've specified a demand for a fuel and don't then have a connection for it. Otherwise, an orphaned fuel can just sit there and doesn't really impact the model.  Having the fuels as small circles as you did might be a good balance - shows the fuel is there, but doesn't detract from the diagram.  Or you do it twice.  Once to check for orphaned fuels, and then with a zero size to create a nice clean diagram...

A shared implementation would be nice.  @abhishek0208 did most of the work on the RES drawing (I just figured out some of the tags that make it look nicer).  I think he's still travelling in Viet Nam, so hopefully he checks in and contributes to this thread soon, and also can chime in on Issue #5 (he's done a bit of work on parsing the data files for a few issues).

Two other pieces (to make the connections right angles in the diagram):
    graph [splines=ortho]
   concentrate=true

I'll try to figure out how to download the viz-res repo and add these items in, but I don't recall how to do it right now.

Cheers,
Taco..

**Comment by willu47** [comment]
Latest visualisation:

image

**Comment by tniet** [comment]
Hey @willu47,

Looking nice!  I can't seem to find the command to include the otoole sub-repository into my OSeMOSYS repository using git so I can work on things.  Can you remind me how to do that?

Thanks,
Taco..

**Comment by willu47** [comment]
> Hey @willu47,
> 
> Looking nice! I can't seem to find the command to include the otoole sub-repository into my OSeMOSYS repository using git so I can work on things. Can you remind me how to do that?
> 
> Thanks,
> Taco..

Hi @tniet - I've now merged this, and put a note in the readme on how to contribute to *otoole*. In short, you can treat *otoole* as a separate entity to OSeMOSYS, and clone it onto your laptop.

**Pull request merged**
