### PR TITLE
Release 1.0

### PR DESCRIPTION
**Pull request by willu47**
Release candidate for version 1.0

### CODE REVIEW

**Comment by trevorb1** [comment]
Hello @willu47! So exciting `v1.0` is getting close to release! 

A couple quick questions/comments: 
1. The docs update in in PR #137 is still in progress. I think the only big thing left to be done is adding info on the validation module. I should have time later this week to do that
2. In issue #56, you have suggested to add a "`setup` command to write the configuration to a file in a user directory". I wasn't quite sure what this entailed, though? 
3. Is there anything else that needs to be done before the `v1.0` release? Taking a look at the project board and milestone board, I think all the other issues have been addressed? 

Thanks so much!!

**Comment by willu47** [comment]
Thanks to you @trevorb1. For 2, I suggest something very simple - copying or writing out an example yaml config file to the path specified by the user.

I think we should gear up for a [JOSS](https://joss.theoj.org/) or [JORS](https://openresearchsoftware.metajnl.com/) submission. Any preferences?  Any alternatives?

**Comment by willu47** [comment]
3. Perhaps let's have a 30 minute catch up at some point to recap on v1.0 functionality - going from fresh install through config to use.

**Comment by trevorb1** [comment]
Thanks @willu47! 
- I have just merged `otoole setup` functionality in PR #144
- I don't currently have any preference between, or alternatives to, JOSS or JORS. I don't actually know how the scope/objectives of each journal differs 😅! I will be sure to have a read over of each of their scopes over the next few days though haha
- Sounds great about having a catch up meeting. I will ping you about setting that up. Thanks!

**Comment by trevorb1** [comment]
Merging this in now! I have tested the install on multiple machines, and tested the upload to PyPI through the use of test.pypi. All tests pass and documentation is up to date! 🎉

**Pull request merged**
