### PR TITLE
Update Objective Cost Calculation 

### LINKED ISSUE #237: [Bug]: Incorrect Total Discounted Cost Calculation
### The Issue

I believe the otoole total discounted cost calculation is not currently taking into account storage costs. 

https://github.com/OSeMOSYS/otoole/blob/cfa2910c17c85f22f5a081e22a768514901161be/src/otoole/results/result_package.py#L581-L663

This issue originated from a bug in the OSeMOSYS objective equation, as described [here](https://github.com/OSeMOSYS/OSeMOSYS_GNU_MathProg/issues/83), with fixes [here ](https://github.com/OSeMOSYS/OSeMOSYS_GNU_MathProg/pull/89)and [here](https://github.com/OSeMOSYS/OSeMOSYS_GNU_MathProg/pull/91). However, the otoole calc has not been updated to reflect these updates. 

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Log output

_No response_

### Operating System

Linux

### What version of otoole are you running?

1.1.3

### Possible Solution

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trevorb1**
### Description

In this PR I have updated the objective cost calculation to account for storage costs. Additionally, I have added result calculations for non-discounted storage investment costs, discounted storage investment costs, discounted storage salvage value, and total discounted cost by storage. 

### Issue Ticket Number

Closes #237 

### Documentation

na

### CODE REVIEW

**Comment by trevorb1** [comment]
@willu47 would you be able to review this? Since Im modifying the objective cost calculation, a double check that everything looks correct would be great! If you dont have time right now though, no worries at all :)

**Comment by trevorb1** [comment]
Oh. Actually, sorry, maybe hold off on reviewing this @willu47. I dont think its working correctly. If no storage is in the model, total discounted cost isnt calculated and this warning comes up. It originates from the fact that if no storage is invested in, `NewStorageCapacity` isnt an available result and the rest of storage calculations fail. Il sort this out and tag you for a review when its fixed!

```
DEBUG:otoole.results.results:Error calculating TotalDiscountedCost: 'Cannot calculate TotalDiscountedCost due to missing data: \'Cannot calculate TotalDiscountedCostByStorage due to missing data: \\\'Cannot calculate DiscountedCapitalInvestmentStorage due to missing data: "Cannot calculate CapitalInvestmentStorage due to missing data: \\\\\\\'NewStorageCapacity is not accessible or available\\\\\\\'"\\\'\''
```

**Comment by willu47** [comment]
> `NewStorageCapacity` isnt an available result

Sounds like a good candidate for a unit test...

**Comment by trevorb1** [comment]
Great! I believe I addressed the issue in this [commit](https://github.com/OSeMOSYS/otoole/pull/240/commits/4e2a6ab61ef11a3ac7b19aab881cc3709805e8fd) and is ready for a review; if you have a chance please, @willu47!

**Pull request merged**
