### PR TITLE
Reads configuration directly from a datapackage

### PR DESCRIPTION
**Pull request by willu47**
Addresses #104 and begins to address #56

- adds a utility function to read a user config directly from a data package
- integrates this into the `otoole.ReadDatapackage` class
- adds a test (currently failing on default values)

### CODE REVIEW

**Comment by HauHe** [comment]
Just for better understanding, will this allow to have parameter in the datapackage that are not in the standard OSeMOSYS code?

**Comment by willu47** [comment]
Hi @HauHe - I think so...  It requires a bit more testing to ensure, but the idea is that if you read in a model from a datapackage, you won't need any extra config files. otoole will use the information in the datapackage to perform conversions from the datapackage to other formats. Ideally, it would then also generate the config file (e.g. a `config.yaml`) which you could pass in if converting from another format. - not yet implemented

**Comment by HauHe** [comment]
Hi @willu47, that would be great! Would come really handy when working/testing with modified versions of OSeMOSYS.

**Comment by willu47** [comment]
Superceded by #110

**Pull request closed without merging**
